polypheny/Polypheny-DB

catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/Statements.java, config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/config/Config.java, config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/ConfigServer.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/config/RuntimeConfig.java, dbms/build.gradle, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/PolyphenyDb.java
Start config server, infromation server and web ui at start-up. The ports are defined using the config manager.
=> Defined start-up procedure

core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/Store.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/JdbcRules.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/JdbcSchema.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/JdbcTable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/PolyphenyDbSchema.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/prepare/PolyphenyDbPrepareImpl.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/rel/rel2sql/RelToSqlConverter.java, core/src/test/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/JdbcTableComputer.java, core/src/test/java/ch/unibas/dmi/dbis/polyphenydb/test/JdbcAdapterTest.java, csv-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/csv/CsvStore.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DmlExecutionEngine.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/PolySchema.java, hsqldb-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/hsqldb/HsqldbStore.java
Add rudimentary support for INSERT, UPDATE and DELETE queries against JDBC data stores.
=> Rudimentary support for DML queries

catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/CatalogImpl.java, core/src/main/codegen/includes/parserImpls.ftl, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/Catalog.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/config/RuntimeConfig.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/SqlCreateTable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableAddIndex.java
ALTER TABLE _table_name_ ADD INDEX _index_name_ ON _column_name_ **USING _type_name_**
=> Allow to specify index type in the sql add index statement

dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/QueryProcessorImpl.java
This PR adds support for partial inserts. This allows to omit fields in the SQL insert statement.
=> Support for partial inserts

core/build.gradle, file-adapter/build.gradle, geode-adapter/build.gradle, mongodb-adapter/build.gradle, pig-adapter/build.gradle, pig-parser/build.gradle
There were some tabs in the `build.gradle` files in the project.
=> Replace tabs with spaces in build.gradle files

core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/StoreManager.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/enumerable/EnumerableInterpretable.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/HostInformation.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/JavaInformation.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/AbstractQueryProcessor.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/SqlProcessorImpl.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/Information.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationCode.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationGraph.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationGroup.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationHtml.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationLink.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManager.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationProgress.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationQueryPlan.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationTable.java, information/src/test/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManagerTest.java, information/src/test/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationServerTest.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/AbstractJdbcStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/HsqldbStore.java, jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java, webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/Crud.java
This PR improves multiple aspects of the information manager itself and its application in Polypheny-DB:
- Add support for removing Information Pages and Information Groups
- Simplify usage of information manager by allowing passing objects instead of ids
- Auto generate id if no id is provided
- Improve the usage of the Information Manager in the JDBC Stores by introducing a AbstractJdbcStore
=> Enhance information manager

core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/StoreManager.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/util/background/BackgroundTask.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/util/background/BackgroundTaskHandle.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/util/background/BackgroundTaskManager.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/JavaInformation.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/AbstractJdbcStore.java, jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java
Util to schedule background tasks. Currently only periodic scheduling is supported. Workload-based scheduling will be added later.
=> Background task scheduler

catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/TransactionHandler.java, catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/XATransactionHandler.java, config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/ConfigServer.java, config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/ConfigWebsocket.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/enumerable/EnumerableInterpretable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/runtime/ResultSetEnumerable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/dialect/JethroDataSqlDialect.java, core/src/test/java/ch/unibas/dmi/dbis/polyphenydb/test/concurrent/ConcurrentTestCommandScript.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/AbstractQueryProcessor.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/SqlProcessorImpl.java, druid-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/druid/DruidDateTimeUtils.java, geode-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/rel/GeodeTable.java, geode-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/util/GeodeUtils.java, geode-adapter/src/test/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/rel/RelationalJdbcExample.java, geode-adapter/src/test/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/simple/SimpleJdbcExample.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManager.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationTable.java, information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/InformationWebSocket.java, information/src/test/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManagerTest.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/AbstractJdbcStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/HsqldbStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/PostgresqlStore.java, jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java, jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsService.java, webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/Crud.java
This PR fixes a bug that caused old entries to be shown in query analyzer. Furthermore, this PR also contains some minor code improvements.
=> Remove old entries in query analyzer

core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/SqlDialect.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/dialect/MonetdbSqlDialect.java, dbms/build.gradle, gradle.properties, jdbc-adapter/build.gradle, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/MonetdbStore.java
This PR adds support for the column store MonetDB.
=> Add support for MonetDB using the JDBC adapter

cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraStore.java, csv-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/csv/CsvStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/HsqldbStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/MonetdbStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/PostgresqlStore.java
This PR contains updates for the decriptions of the stores displayed in the UI.
=> Update store descriptions

README.md, catalog/src/main/resources/catalogSchema.sql, csv-adapter/src/main/java/org/polypheny/db/adapter/csv/CsvSchema.java, csv-adapter/src/main/java/org/polypheny/db/adapter/csv/CsvStore.java, csv-adapter/src/main/resources/hr/depts.csv, csv-adapter/src/main/resources/hr/emps.csv
This PR adds support for loading csv files from the classpath. Furthermore, it updates the default schema to read the HR CSV files from classpath.
=> Deliver example schema with CSV adapter

config/src/main/java/org/polypheny/db/config/ConfigClazz.java, core/src/main/java/org/polypheny/db/config/RuntimeConfig.java, core/src/main/java/org/polypheny/db/jdbc/PolyphenyDbResultSet.java, core/src/main/java/org/polypheny/db/jdbc/PolyphenyDbSignature.java, core/src/main/java/org/polypheny/db/prepare/PolyphenyDbPrepareImpl.java, core/src/main/java/org/polypheny/db/routing/ExecutionTimeMonitor.java, core/src/main/java/org/polypheny/db/routing/Router.java, core/src/main/java/org/polypheny/db/sql/ddl/SqlDropTable.java, core/src/main/java/org/polypheny/db/sql/ddl/altertable/SqlAlterTableDropPlacement.java, core/src/main/java/org/polypheny/db/type/PolyType.java, core/src/main/java/org/polypheny/db/util/background/BackgroundTaskHandle.java, core/src/main/java/org/polypheny/db/util/background/BackgroundTaskManager.java, dbms/build.gradle, dbms/src/main/java/org/polypheny/db/information/JavaInformation.java, dbms/src/main/java/org/polypheny/db/processing/AbstractQueryProcessor.java, dbms/src/main/java/org/polypheny/db/processing/SqlProcessorImpl.java, dbms/src/main/java/org/polypheny/db/router/AbstractRouter.java, dbms/src/main/java/org/polypheny/db/router/IcarusRouter.java, dbms/src/main/java/org/polypheny/db/router/RouterFactory.java, dbms/src/main/java/org/polypheny/db/router/RouterManager.java, dbms/src/main/java/org/polypheny/db/router/SimpleRouter.java, gradle.properties, information/src/main/java/org/polypheny/db/information/InformationTable.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/PolyphenyDbStatementHandle.java, webui/src/main/java/org/polypheny/db/webui/Crud.java
Implementation of a query router which classifies queries based on their structure and learns the execution time for all underlying stores based on this classification.
=> Icarus routing

jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/rel2sql/SqlImplementor.java
Fix an issue which prevents insertion of null values.
=> Fix handling of null values in SQL Implementor

catalog/src/main/java/org/polypheny/db/catalog/CatalogImpl.java, core/src/main/java/org/polypheny/db/plan/volcano/VolcanoPlanner.java, core/src/main/java/org/polypheny/db/processing/QueryProcessor.java, core/src/main/java/org/polypheny/db/rel/rules/ProjectRemoveRule.java, core/src/test/java/org/polypheny/db/test/HepPlannerTest.java, dbms/src/main/java/org/polypheny/db/PolyphenyDb.java, dbms/src/main/java/org/polypheny/db/processing/AbstractQueryProcessor.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcDdlTest.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcPreparedStatementsTest.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/JdbcConvention.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/rel2sql/SqlImplementor.java, jdbc-adapter/src/test/java/org/polypheny/db/adapter/jdbc/rel2sql/RelToSqlConverterTest.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java
This PR improves the column mapping on JDBC stores. Furthermore, this PR fixes an issue with prepared batch updates and an issue with dropping foreign keys.
=> Improve column mapping for JDBC stores

dbms/src/main/java/org/polypheny/db/processing/ImplementationCache.java, dbms/src/main/java/org/polypheny/db/processing/QueryParameterizer.java, dbms/src/main/java/org/polypheny/db/processing/QueryPlanCache.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcPreparedStatementsTest.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/ResultSetEnumerable.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/connection/ConnectionHandler.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/connection/TransactionalConnectionFactory.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/connection/XaConnectionFactory.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/stores/HsqldbStore.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/stores/MonetdbStore.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/stores/PostgresqlStore.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java
This PR improves the handling of arrays and adds support for arrays in JDBC prepared statements and batch statements.
=> Improve array handling

jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java
This PR fixes an issue with transactions only consisting of DDL statements submitted through the JDBC interface.
=> Add missing commit for DDL queries on JDBC interface

core/src/main/java/org/polypheny/db/adapter/DataContext.java, core/src/main/java/org/polypheny/db/adapter/enumerable/EnumerableLimit.java, core/src/main/java/org/polypheny/db/adapter/enumerable/RexToLixTranslator.java, core/src/main/java/org/polypheny/db/config/RuntimeConfig.java, core/src/main/java/org/polypheny/db/plan/VisitorDataContext.java, core/src/main/java/org/polypheny/db/processing/QueryProcessor.java, core/src/main/java/org/polypheny/db/rex/RexDynamicParam.java, core/src/main/java/org/polypheny/db/rex/RexLiteral.java, core/src/main/java/org/polypheny/db/schema/Schemas.java, core/src/main/java/org/polypheny/db/sql/ddl/SqlCreateTable.java, core/src/main/java/org/polypheny/db/util/BuiltInMethod.java, core/src/test/java/org/polypheny/db/rex/RexExecutorTest.java, core/src/test/java/org/polypheny/db/test/InterpreterTest.java, core/src/test/java/org/polypheny/db/test/RexProgramBuilderBase.java, dbms/src/main/java/org/polypheny/db/processing/AbstractQueryProcessor.java, dbms/src/main/java/org/polypheny/db/processing/DataContextImpl.java, dbms/src/main/java/org/polypheny/db/processing/DataMigratorImpl.java, dbms/src/main/java/org/polypheny/db/processing/QueryParameterizer.java, dbms/src/main/java/org/polypheny/db/router/AbstractRouter.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcDdlTest.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/ResultSetEnumerable.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/rel2sql/SqlImplementor.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java, statistic/src/main/java/org/polypheny/db/statistic/StatisticsManager.java
This PR adds support for internal processing of batched queries.
=> Batch query processing

catalog/src/main/java/org/polypheny/db/catalog/CatalogImpl.java, dbms/src/main/java/org/polypheny/db/ddl/DdlManagerImpl.java, dbms/src/main/java/org/polypheny/db/information/HostInformation.java, file-adapter/src/main/java/org/polypheny/db/adapter/file/FileStore.java, webui/src/main/java/org/polypheny/db/webui/Crud.java, webui/src/main/java/org/polypheny/db/webui/models/ForeignKey.java
And other minor improvements:
- Refreshable FileStore disk usage graph
- Renaming ForeignKey model
- Drop foreign keys when dropping data sources
- Add missing exception when creating foreign keys
=> Improve handling of foreign keys

core/build.gradle, core/src/main/java/org/polypheny/db/config/RuntimeConfig.java, core/src/main/java/org/polypheny/db/transaction/Statement.java, core/src/main/java/org/polypheny/db/util/FileInputHandle.java, core/src/main/java/org/polypheny/db/util/SharedInputStream.java, dbms/src/main/java/org/polypheny/db/processing/ParameterValueValidator.java, dbms/src/main/java/org/polypheny/db/transaction/StatementImpl.java, dbms/src/main/java/org/polypheny/db/transaction/TransactionImpl.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcDmlTest.java, file-adapter/src/main/java/org/polypheny/db/adapter/file/FileEnumerator.java, file-adapter/src/main/java/org/polypheny/db/adapter/file/FileModifier.java, file-adapter/src/main/java/org/polypheny/db/adapter/file/FileStore.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/ResultSetEnumerable.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/PolyphenyDbStatementHandle.java, rest-interface/src/main/java/org/polypheny/db/restapi/HttpRestServer.java, rest-interface/src/main/java/org/polypheny/db/restapi/Rest.java, webui/src/main/java/org/polypheny/db/webui/Crud.java
This PR fixes the issue with inserting and updating replicated multimedia columns. It introduces a FileInputHandler which wraps multimedia data. Furthermore, this also fixes some resource issues when inserting or updating multimedia columns.
=> Improve support for multimedia data with replicated columns

.github/workflows/docker.yml, .github/workflows/integration.yml, .github/workflows/matrix.yml, dbms/src/test/java/org/polypheny/db/TestHelper.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcDdlTest.java, dbms/src/test/java/org/polypheny/db/misc/HorizontalPartitioningTest.java, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/ResultSetEnumerable.java, mongodb-adapter/src/main/java/org/polypheny/db/adapter/mongodb/MongoFilter.java, mongodb-adapter/src/main/java/org/polypheny/db/adapter/mongodb/MongoProject.java, mongodb-adapter/src/main/java/org/polypheny/db/adapter/mongodb/MongoRules.java
This PR improves the continuous integration pipeline and fixes and issue with the test helper. Furthermore, this PR fixes an issue with the array item operator on MongoDB and improves the handling of floating point values on JDBC stores.
=> Improve continuous integration pipeline

CHANGELOG.md, gradle.properties
This PR prepares for the next development cycle.
* Set version number to `0.8.1-SNAPSHOT`
* Update the changelog file
=> Heading for version 0.8.1

.github/workflows/docker.yml, .github/workflows/integration.yml, .github/workflows/matrix.yml, core/src/main/java/org/polypheny/db/StatisticsManager.java, dbms/src/main/java/org/polypheny/db/PolyphenyDb.java, dbms/src/main/java/org/polypheny/db/transaction/TransactionImpl.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/NumericalStatisticColumn.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/StatisticColumn.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/StatisticTable.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/StatisticsManagerImpl.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/TemporalStatisticColumn.java, plugins/cypher-language/src/main/java/org/polypheny/db/cypher/expression/CypherGate.java, plugins/mongodb-adapter/src/main/java/org/polypheny/db/adapter/mongodb/MongoEntity.java, plugins/mql-language/src/main/codegen/DocumentParser.jj, plugins/neo4j-adapter/src/main/java/org/polypheny/db/adapter/neo4j/Neo4jPlugin.java, plugins/neo4j-adapter/src/main/java/org/polypheny/db/adapter/neo4j/util/NeoStatements.java, webui/src/main/java/org/polypheny/db/webui/Crud.java
**Fixes:**#437
* Removes Generics from `StatisticManager` and NumericalStatistics
* Changes comparison of TemporalStatistics to since Epoch
* Introduces correct handling of logical operators for properties in graph
* Manual build step for Github workloads
---
* Deployment via Docker lead to `NullPointerException`
* `IllegalArgumentException`, when graph contains an '_'
* Comparison of TemporalStatistics lead to error
---
=> Fix for Graph Naming Error, Docker Deploy, Numerical Statistics, Logical Operator in Graph Properties

CHANGELOG.md, core/src/main/java/org/polypheny/db/plugins/PolyPluginManager.java, dbms/build.gradle, dbms/src/main/java/org/polypheny/db/gui/AboutWindow.java, gradle.properties
This PR prepares for the next development cycle. Furthermore, it contains changes made on the release branch for version `0.9.0`.
- Set version to `0.10.0-SNAPSHOT`
- Bundle plugins into jar file
- Adjust year in splash screen
- Update change log
=> Preparing for next development cycle

dbms/src/main/java/org/polypheny/db/PolyphenyDb.java
Set default locale to Locale.US to avoid decimate formatting issues.
=> Set Default Locale

dbms/src/main/java/org/polypheny/db/gui/AboutWindow.java, gradle.properties
Version 0.10.0 has been released and this PR increases the version number to 0.10.1 to start the next development cycle. Furthermore, this PR updates the current year in the about window.
=> Increase version number for next development cycle

plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/WorkflowApi.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/WorkflowManager.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/WorkflowPlugin.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/dag/activities/ActivityRegistry.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/dag/activities/impl/load/DocLoadActivity.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/dag/activities/impl/load/LpgLoadActivity.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/dag/activities/impl/load/RelLoadActivity.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/engine/scheduler/GlobalScheduler.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/engine/storage/QueryUtils.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/engine/storage/StorageManagerImpl.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/jobs/CronScheduler.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/jobs/JobManager.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/jobs/JobTrigger.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/jobs/ScheduledJob.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/models/ActivityModel.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/AbstractSession.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/ApiSession.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/JobSession.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/NestedSession.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/NestedSessionManager.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/SessionManager.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/UserSession.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/session/WorkflowWebSocket.java, plugins/workflow-engine/src/test/java/org/polypheny/db/workflow/engine/scheduler/GlobalSchedulerTest.java, plugins/workflow-engine/src/test/java/org/polypheny/db/workflow/engine/scheduler/WorkflowSchedulerTest.java, plugins/workflow-engine/src/test/java/org/polypheny/db/workflow/engine/storage/StorageManagerTest.java
This contains various improvements for the workflow engine:
- Adjust visibility of fields
- Remove unused/unreachable code
- Reduce use of global variables
- Use `GenericRuntimeException`s instead of `RuntimeException`s
- Use parameterized log messages
=> Workflow engine improvements
