polypheny/Polypheny-DB

catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/CatalogImpl.java, catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/Statements.java, catalog/src/main/resources/catalogSchema.sql, core/_docs/reference.md, core/src/main/codegen/config.fmpp, core/src/main/codegen/includes/ddlParser.ftl, core/src/main/codegen/includes/parserImpls.ftl, core/src/main/codegen/templates/Parser.jj, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/Catalog.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/entity/CatalogForeignKey.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/exceptions/UnknownForeignKeyOptionException.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/exceptions/UnknownIndexException.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/exceptions/UnknownIndexTypeException.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/SqlCreateTable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/SqlDropTable.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/SqlKeyConstraint.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableAddForeignKeyConstraint.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableAddIndex.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableAddPrimaryKey.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableAddUniqueConstraint.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableDropConstraint.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableDropIndex.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/altertable/SqlAlterTableDropPrimaryKey.java, gradle.properties, jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java
Add support for the following statements:
ALTER TABLE [ _database_name_ . ] [ _schema_name_ . ] _table_name_
- ADD PRIMARY KEY _column_name_
- ADD PRIMARY KEY (_column_name_, column_name, ...)
- DROP PRIMARY KEY
- ADD CONSTRAINT _constraint_name_ UNIQUE  _column_name_
- ADD CONSTRAINT _constraint_name_ UNIQUE (_column_name_, column_name, ...)
- ADD CONSTRAINT _constraint_name_ FOREIGN KEY _column_name_ REFERENCES [ databaseName . ] [ schemaName . ] tableName (_column_name_, column_name, ...) [ ON UPDATE ( CASCADE | RESTRICT | SET NULL | SET DEFAULT ) ] [ ON DELETE ( CASCADE | RESTRICT | SET NULL | SET DEFAULT ) ]
- ADD CONSTRAINT _constraint_name_ FOREIGN KEY (_column_name_, column_name, ...) REFERENCES [ databaseName . ] [ schemaName . ] tableName (_column_name_, column_name, ...) [ ON …
=> Managing keys and constraints using SQL

catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/CatalogImpl.java, catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/Statements.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/SqlInsert.java, core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/ddl/SqlDropTable.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/QueryProcessorImpl.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/TransactionImpl.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/schema/PolySchemaBuilder.java, dbms/src/test/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/JdbcMetaTest.java
- Allow the columns in a SQL insert statement to have an arbitrary order 
- Ensure that columns which are part of the primary key are not nullable 
- Simplify dropping of tables with self-referencing foreign keys
- Check if the data type of the referenced column of a foreign key constraint matches the data type of the referencing column
=> Improve query handling

webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/SchemaToJsonMapper.java, webui/src/test/java/ch/unibas/dmi/dbis/polyphenydb/webui/SchemaToJsonMapperTest.java
This PR adds a helper class that allows exporting the definition of a table as JSON. The JSON includes
- The table name (without schema part)
- The column definitions (name, type, length, scale, nullability, default value)
- The primary key
It can be selected whether the default values and the primary key definition should be included in the export.
Furthermore, the helper class supports creating a `CREATE TABLE` statement based on such a JSON. In can be selected whether the statement should define a primary key and default values. The schema name can be specified. It is also possible to specify the name of the data store the table should be placed on.
=> Helper for exporting table definitions as json

core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/Store.java, csv-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/csv/CsvStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/HsqldbStore.java, jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/PostgresqlStore.java
This changes how a store is informed about changed settings. Instead of being told about changes one by one, it now simply gets a list of settings that changed.
This also includes a small fix to the shutdown method of the PostgreSQL store.
=> Improve settings management in stores + minor fixes to Store

csv-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/csv/CsvStore.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/AbstractQueryProcessor.java, dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/TransactionImpl.java, webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/Crud.java, webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/models/Result.java
With #156 we broke support for certain queries in the query plan builder. This PR further improves query processing and fixes support for these logical query plans in the query plan builder.
Steps to reproduce the issue: 
Add a table scan to the query plan builder (e.g. from table emps) and execute it.
This PR also improves the error reporting in the UI.
=> Fix query plan builder

core/_docs/reference.md, core/src/main/codegen/config.fmpp, core/src/main/codegen/includes/parserImpls.ftl, core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/polypheny/db/sql/ddl/SqlAlterStoresAdd.java, core/src/main/java/org/polypheny/db/sql/ddl/SqlAlterStoresDrop.java
This PR adds support for deploying and removing stores using SQL.
Deploy a store:
```ALTER STORES ADD storeName USING adapterClass WITH configAsJson```
Remove a store
```ALTER STORES DROP storeName```
=> SQL support for deploying and removing stores

build.gradle, core/src/main/java/org/polypheny/db/sql/ddl/altertable/SqlAlterTableDropPlacement.java, dbms/src/main/java/org/polypheny/db/router/IcarusRouter.java, dbms/src/main/java/org/polypheny/db/router/RouterManager.java, information/src/main/java/org/polypheny/db/information/InformationManager.java, information/src/main/java/org/polypheny/db/webui/InformationServer.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java, webui/build.gradle, webui/src/main/java/org/polypheny/db/webui/Crud.java
This PR includes several improvements for Icarus routing:
- DML queries are now also working for more than two stores.
- Correctly remove stores from the routing table if the corresponding placement has been dropped.
- Fix an issue in the routing table calculation which could have caused sum of values > 100.
- Adding additional configuration options for Icarus routing.
- Checking whether all stores report the same number of rows changed for DML queries.
Furthermore, this PR improves the handling of requests for unknown information pages in the information manager.
=> Improvements for Icarus routing

dbms/build.gradle, jdbc-adapter/src/main/java/org/polypheny/db/adapter/jdbc/stores/PostgresqlStore.java, jdbc-interface/src/main/java/org/polypheny/db/jdbc/DbmsMeta.java
This PR disables the locking on underlying data stores where possible. Furthermore, this PR fixes failing integration tests.
=> Disable locking on underlying data stores 

core/src/main/java/org/polypheny/db/sql/ddl/SqlDropTable.java, dbms/src/main/java/org/polypheny/db/router/AbstractRouter.java, dbms/src/main/java/org/polypheny/db/router/IcarusRouter.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcDmlTest.java, dbms/src/test/java/org/polypheny/db/misc/VerticalPartitioningTest.java
This PR fixes the following issues with the query routing for partitioned tables:
- A bug in the placement selection of Icarus routing which lead to unrouteable plans.
- An issue with dropping partitioned tables
- An issue with batch inserts into vertically partitioned tables
Furthermore, this PR adds additional tests.
=> Improve query routing for partitioned scenarios

rest-interface/src/main/java/org/polypheny/db/restapi/RequestParser.java, rest-interface/src/test/java/org/polypheny/db/restapi/RequestParserTest.java
The `RequestParser.parseFilterOperation` method checked for `filterString` that begin with `<` and `>` before `<=` and `>=`. This might cause filter operations for `>=` or `<=` to be falsely associated with the `>` and `<` operator and might cause an exception (For example, `public.emps.empid=>=100`. Here the operator will be falsely identified as `>` and the operand as `=10`, which will later cause a parse exception since it cannot be parsed to an integer.
This PR solves this issue.
=> Fix issue with filter operations on REST interface

dbms/src/main/java/org/polypheny/db/information/JavaInformation.java, information/src/main/java/org/polypheny/db/information/GraphColor.java, information/src/main/java/org/polypheny/db/information/InformationGraph.java
[Related PR for the UI.](https://github.com/polypheny/Polypheny-UI/pull/74)
**Fixes:** [Allow to specifiy colors for graphs #284](https://github.com/polypheny/Polypheny-DB/issues/284)
- GraphColor Enum added
- Informationgraph extended by colorList (List of GraphColor Enum) erweitert. 
- This set method of the colorList overrides the default list of colors. This avoids changing the signature of the constructor and makes setting a custom order of columns optional.
=> Allow to specify colors for information graphs

monitoring/src/main/java/org/polypheny/db/monitoring/core/MonitoringQueueImpl.java
**Change**: added the monitoring of threads by logging the new number of threads whenever there is a change (fixes #395)
**Implementation**:
Incorporated another thread in `MonitoringQueueImpl.java` which checks the change in number of threads every 500 milliseconds, and logs the info whenever there is a change as necessary.
**Possible points of concern:**
- I created a separate thread which uses getters from ThreadPoolExecutor, so I had to lock all methods which used ThreadPoolExecutor, which may affect performance.
- All changes are nested into main() since it is fairly short, so further refactoring may be necessary.
- Changing 500 ms into other periods, or perhaps using another solution altogether. Since there is no hook for ThreadPoolExecutor to see when threads change, I currently …
=> Monitoring threads

CHANGELOG.md, gradle.properties
This PR prepares for the next development cycle.
Changes
* Set version number to `0.8.2-SNAPSHOT`
* Update the changelog file
=> Heading for version 0.8.2

dbms/src/main/java/org/polypheny/db/PolyphenyDb.java
Fixed #424 
Added additional command line option `-v` & `--version` to retrieve currently installed version of Polypheny-DB
---
=> Add '-version' as command line option

core/build.gradle, plugins/cql-language/build.gradle, plugins/cypher-language/build.gradle, plugins/mql-language/build.gradle, plugins/pig-language/build.gradle, plugins/sql-language/build.gradle
New version of the JavaCC plugin is out: [release notes](https://github.com/javacc/javaccPlugin/releases/tag/javacc-gradle-plugin-3.0.0). Because the plugin ID changed, it won't be found by usual dependency update mechanisms, so I'm making  PRs manually to update all the major projects on GitHub that are using an older version of the plugin.
The new version should make compilation of the parser a bit faster and improve compatibility with future releases of Gradle.
I locally checked that `./gradlew test -Dstore.default=file` is successful with this change, but have not done any other testing.
* Update Gradle JavaCC plugin to latest version (3.0.0)
=> Update Gradle JavaCC plugin to latest version (3.0.0)

core/src/main/java/org/polypheny/db/algebra/core/SetOp.java, core/src/main/java/org/polypheny/db/catalog/impl/PolyCatalog.java, core/src/main/java/org/polypheny/db/catalog/logistic/DataModel.java, core/src/main/java/org/polypheny/db/rex/RexBuilder.java, core/src/main/java/org/polypheny/db/rex/RexUnknownAs.java, core/src/main/java/org/polypheny/db/util/MonikerImpl.java, core/src/main/java/org/polypheny/db/util/NameMatchers.java, core/src/main/java/org/polypheny/db/util/PrecedenceClimbingParser.java, core/src/main/java/org/polypheny/db/util/Util.java, core/src/test/java/org/polypheny/db/util/UtilTest.java, plugins/cypher-language/src/main/java/org/polypheny/db/cypher/expression/CypherLiteral.java, plugins/mongodb-adapter/src/main/java/org/polypheny/db/adapter/mongodb/util/RexToMongoTranslator.java, plugins/neo4j-adapter/src/main/java/org/polypheny/db/adapter/neo4j/util/NeoUtil.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/DbMetaRetriever.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/PIService.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/relational/RelationalMetaRetriever.java, plugins/sql-language/src/main/java/org/polypheny/db/sql/language/SqlIdentifier.java, plugins/sql-language/src/main/java/org/polypheny/db/sql/language/validate/IdentifierNamespace.java, plugins/sql-language/src/test/java/org/polypheny/db/sql/language/utils/AbstractSqlTester.java, webui/src/main/java/org/polypheny/db/webui/crud/CatalogCrud.java
This PR adds log statements during benchmarks when error responses are returned in the prism interface.
Usually, we do not want to log error messages that are returned to the user via the interface since errors are very common (e.g., typo in an entity name or wrong syntax). However, in benchmarks, there should be no wrong queries.
Included are also some conversions of switch statements to switch expressions and replacing a `Util` method with a method included in the standard library.
=> Log Prism Error Responses in Benchmark Mode

core/src/main/java/org/polypheny/db/algebra/core/CorrelationId.java, core/src/main/java/org/polypheny/db/functions/Functions.java, core/src/main/java/org/polypheny/db/languages/LanguageManager.java, core/src/main/java/org/polypheny/db/type/entity/PolyValue.java, core/src/main/java/org/polypheny/db/util/ByteString.java, core/src/main/java/org/polypheny/db/util/CaseInsensitiveComparator.java, dbms/src/main/java/org/polypheny/db/processing/DataContextImpl.java, dbms/src/main/java/org/polypheny/db/transaction/LockManager.java, dbms/src/main/java/org/polypheny/db/transaction/TransactionImpl.java, dbms/src/test/java/org/polypheny/db/jdbc/JdbcPreparedStatementsTest.java, dbms/src/test/java/org/polypheny/db/sql/view/ComplexViewTest.java, plugins/cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/util/CottontailTypeUtil.java, plugins/jdbc-adapter-framework/src/main/java/org/polypheny/db/adapter/jdbc/ResultSetEnumerable.java, plugins/jdbc-adapter-framework/src/main/java/org/polypheny/db/adapter/jdbc/stores/AbstractJdbcStore.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/PIClient.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/PIService.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statementProcessing/StatementProcessor.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/PIPreparedIndexedStatement.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/PIPreparedNamedStatement.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/PIPreparedStatement.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/PIStatement.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/PIUnparameterizedStatement.java, plugins/prism-interface/src/main/java/org/polypheny/db/prisminterface/statements/StatementManager.java
The main contribution of this PR are improvements to transaction handling in the Prism driver and decimal validation:
- Ensure that statements objects used in the Prism driver belong to the current transaction (with a test that would have exposed this)
- Ignore leading 0 in decimal number validation to match the documentation
- Throw an exception when trying to create a statement for an inactive transaction (this exposed an issue in `anyPrepareQuery`)
- Improve type derivation in prepared statements
- Replace a few subtractions with the more appropriate `Integer.compare`
=> Improve transaction handling in Prism Driver & Decimal validation

core/src/main/java/org/polypheny/db/docker/DockerContainer.java, core/src/main/java/org/polypheny/db/docker/PolyphenyTlsClient.java
This sets TCP_NODELAY on sockets used to communicate with stores deployed on Docker.  This leads to a massive speedup (e.g. the YCSB benchmark shows a 4-5 time speedup for stores deployed on Docker).
=> Add TCP_NODELAY to proxy connections and PolyphenyTlsClient

core/src/main/java/org/polypheny/db/adapter/AdapterManager.java, core/src/main/java/org/polypheny/db/adapter/DeployMode.java, plugins/neo4j-adapter/src/main/java/org/polypheny/db/adapter/neo4j/Neo4jPlugin.java
With this change it is again possible to connect to use remote neo4j stores (i.e. not managed by Polypheny via Docker) .  This also exposed an issue where settings are taken as-is when creating an adapter, even when they contain entries which do not apply to the current deploy mode (e.g. password when deploying via Docker).  So fix this by filtering out all entries that do not apply to the deploy mode when creating an adapter.
- Remote deployment of neo4j stores
- Filter out settings that do not apply to the current mode when creating an adapter
=> Fix Neo4j remote deployment

core/src/main/java/org/polypheny/db/nodes/Node.java, core/src/main/java/org/polypheny/db/processing/QueryContext.java, plugins/mql-language/src/main/java/org/polypheny/db/languages/mql/MqlCreateView.java, plugins/mql-language/src/main/java/org/polypheny/db/languages/mql/MqlRenameCollection.java
`getNamespaceId` is never overridden and returns the default namespace id, which cannot be correct in general.  So remove it and replace all uses with other methods to get an appropriate namespace id.
=> Remove method `getNamespaceId `

core/src/main/java/org/polypheny/db/algebra/logical/relational/LogicalRelViewScan.java, core/src/main/java/org/polypheny/db/catalog/catalogs/LogicalRelationalCatalog.java, core/src/main/java/org/polypheny/db/catalog/entity/logical/LogicalMaterializedView.java, core/src/main/java/org/polypheny/db/catalog/entity/logical/LogicalView.java, core/src/main/java/org/polypheny/db/catalog/impl/PolyCatalog.java, core/src/main/java/org/polypheny/db/catalog/impl/logical/RelationalCatalog.java, core/src/main/java/org/polypheny/db/catalog/snapshot/LogicalRelSnapshot.java, core/src/main/java/org/polypheny/db/catalog/snapshot/impl/LogicalRelSnapshotImpl.java, core/src/test/java/org/polypheny/db/snapshot/MockRelSnapshot.java, dbms/src/main/java/org/polypheny/db/view/MaterializedViewManagerImpl.java, dbms/src/test/java/org/polypheny/db/sql/view/BasicMaterializedViewTest.java, dbms/src/test/java/org/polypheny/db/sql/view/ViewTest.java, plugins/sql-language/src/main/java/org/polypheny/db/sql/language/ddl/SqlCreateView.java
This PR fixes various issues with views during rollback and restore.
- Views are now correctly serialized and restored to `LogicalView` or `LogicalMaterializedView` respectively.
- The `collation` field was removed from `LogicalView` to make the serialization easier.  The content of the `collation` field is now stored in the `LogicalRelationalCatalog` in the `collations` map (like the `AlgNode`s related to a view are already stored in a `nodes` map).
- When restoring the Catalog (when Polypheny is started), the `nodes` and `collations` maps are re-populated, as they are not serialized with the Catalog.
=> Rollback/restore with (materialized) views

core/src/main/java/org/polypheny/db/catalog/entity/logical/LogicalTable.java, core/src/main/java/org/polypheny/db/catalog/entity/logical/LogicalView.java, core/src/main/java/org/polypheny/db/docker/AutoDocker.java, core/src/main/java/org/polypheny/db/docker/DockerContainer.java, core/src/main/java/org/polypheny/db/docker/DockerInstance.java, core/src/main/java/org/polypheny/db/docker/DockerSetupHelper.java, core/src/main/java/org/polypheny/db/docker/PolyphenyHandshakeClient.java, core/src/main/java/org/polypheny/db/type/PolySerializable.java
This PR removes unused code, replaces a few casts in favor of pattern variables and updates Docker related log messages to use constant strings.
=> Remove unused code and various small improvements

core/src/main/java/org/polypheny/db/adapter/DataStore.java, plugins/monetdb-adapter/src/main/java/org/polypheny/db/adapter/monetdb/stores/MonetdbStore.java
According to the [MonetDB documentation](https://www.monetdb.org/documentation-Aug2024/user-guide/sql-manual/data-definition/index-definitions/), `CREATE INDEX` statements are treated as advice only.  Because of this it was previously it was an error to create an index on a MonetDB store.  With this PR this is not longer an error and we execute an appropriate `CREATE INDEX` statement on the MonetDB store (although MonetDB may treat it as advisory and ignore it).
=> Add indexes to MonetDB

core/src/main/java/org/polypheny/db/config/RuntimeConfig.java, core/src/main/java/org/polypheny/db/docker/DockerContainer.java
This way we can measure the performance without the added overhead of TLS (we also do not use TLS connections for other stores in benchmarks).  Add a config option (`DOCKER_DIRECT_CONNECTION`) to disable direct connections so that the TLS overhead can be benchmarked.
=> Connect directly to Docker containers in benchmark mode

core/src/main/java/org/polypheny/db/functions/Functions.java, core/src/main/java/org/polypheny/db/rex/RexSimplify.java, core/src/main/java/org/polypheny/db/util/EquivalenceSet.java, core/src/test/java/org/polypheny/db/util/ImmutableBitSetTest.java, core/src/test/java/org/polypheny/db/util/UtilTest.java, monitoring/src/main/java/org/polypheny/db/monitoring/statistics/StatisticRepository.java, plugins/sql-language/src/main/java/org/polypheny/db/sql/language/SqlDialect.java, plugins/sql-language/src/test/java/org/polypheny/db/sql/language/FunctionsTest.java
- Return the result directly from set operations without constructing a new ArrayList
- Use `Set.copyOf()` instead of `new HashSet()`
- Remove the unused `BUILT_IN_OPERATORS_LIST` set
=> Improve set related operations

core/src/main/java/org/polypheny/db/catalog/impl/logical/RelationalCatalog.java, dbms/src/main/java/org/polypheny/db/ddl/DdlManagerImpl.java, webui/src/main/java/org/polypheny/db/webui/Crud.java
This PR fixes various issues related to updating columns.
- It is no longer possible to set the nullable flag for fields that are part of a primary key
- Update `collectionType` when changing the column type
- Do not update the default value when the old and new default value are both `NULL`
- Return after the first update statement that fails.  Previously it reported the status of the last statement, which might be success even with previous statements failing.
=> Improve code related to updating columns

plugins/jdbc-adapter-framework/src/main/java/org/polypheny/db/adapter/jdbc/JdbcUtils.java
In Polypheny's implementation of querries, result set values are processed using a switch statement that distinguishes between data types. However, the case for binary data was missing, which could lead to a crash when such data is encountered. This commit adds the missing case to handle binary data properly, resolving the associated error.
=> Fix missing binary data handling in result set type switch

core/src/main/java/org/polypheny/db/adapter/AdapterManager.java, core/src/main/java/org/polypheny/db/catalog/Catalog.java, core/src/main/java/org/polypheny/db/catalog/IdBuilder.java, core/src/main/java/org/polypheny/db/catalog/impl/PolyCatalog.java, core/src/main/java/org/polypheny/db/catalog/snapshot/Snapshot.java, core/src/main/java/org/polypheny/db/catalog/snapshot/impl/SnapshotImpl.java, core/src/main/java/org/polypheny/db/iface/QueryInterfaceManager.java, core/src/test/java/org/polypheny/db/snapshot/MockSnapshot.java, dbms/src/main/java/org/polypheny/db/ddl/DdlManagerImpl.java, dbms/src/main/java/org/polypheny/db/ddl/DefaultInserter.java, dbms/src/test/java/org/polypheny/db/TestHelper.java, plugins/mql-language/src/test/java/org/polypheny/db/mql/mql2alg/MqlMockCatalog.java, plugins/workflow-engine/src/main/java/org/polypheny/db/workflow/engine/storage/StorageManagerImpl.java, webui/src/main/java/org/polypheny/db/webui/Crud.java, webui/src/main/java/org/polypheny/db/webui/models/catalog/SnapshotModel.java
Move the bookkeeping of adapter and query interface templates out of the catalog into the `AdapterManager` and `QueryInterfaceManager` respectively.  This way adapter/query interface template addition/removal (corresponding to loading/unloading plugins) does not interfere with other catalog modifications.
=> Manage adapter and query interface templates in the corresponding manager classes

core/src/main/java/org/polypheny/db/catalog/entity/logical/LogicalTable.java, dbms/src/main/java/org/polypheny/db/ddl/DdlManagerImpl.java, plugins/jdbc-adapter-framework/src/main/java/org/polypheny/db/adapter/jdbc/sources/AbstractJdbcSource.java, plugins/monetdb-adapter/src/main/java/org/polypheny/db/adapter/monetdb/sources/MonetdbSource.java, plugins/mysql-adapter/src/main/java/org/polypheny/db/adapter/jdbc/MysqlSourcePlugin.java, plugins/postgres-adapter/src/main/java/org/polypheny/db/adapter/postgres/source/PostgresqlSource.java, webui/src/main/java/org/polypheny/db/webui/Crud.java
This improves various aspects related to sources:
- Restore JDBC source tables on startup
- Improve comparison of logical tables: tables without primary key will no longer be considered equal
- When a source table contains a primary key, add this information to the logical table
- Reduce code duplication between JDBC sources
- Add missing error handling to `Crud#getTable`
=> Various source improvements
